FROM node:12 as build

COPY [".", "."]
RUN npm ci && npm run build

FROM node:slim-12

USER node
EXPOSE 3000

COPY --from=build /home/node/app/dist /home/node/app/package.json /home/node/app/package-lock.json ./
RUN npm ci --production

CMD [ "node", "dist/src/index.js" ]
